# Generated by Django 5.0.6 on 2024-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uber", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uberrequest",
            name="pickup_location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
