# Generated by Django 5.0.6 on 2024-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uber", "0006_driver_address_driver_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="uberrequest",
            name="estimated_arrival_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
